{% set name = "taskipy" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3dd7c53f7c9c4fd17dc908b1037f545afc452907eb0953b84e91c0a9a9d809d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - task = taskipy.cli:main

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python
    - pip
    - poetry
    - __unix  # [unix]
    - __win   # [win]
    - colorama >=0.4.4
    - mslex >=0.3.0  # [win]
    - psutil >=5.7.2
    - tomli >=2.0.1

test:
  imports:
    - taskipy
  requires:
    - pip
  commands:
    - pip check
    - task --help

about:
  home: https://github.com/taskipy/taskipy
  summary: 'The complementary task runner for python projects'
  description: |
    Every development pipeline has tasks, such as test, lint or publish.
    With taskipy, you can define those tasks in one file and run them with a simple command.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/taskipy/taskipy

extra:
  recipe-maintainers:
    - Zeitsperre
    - illBeRoy
