{% set name = "taskipy" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d9631c29980481d59858f0a100ed3200cf7468ca8c0540ef19388586485532d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - task = taskipy.cli:main

requirements:
  host:
    - python
    - pip
    - poetry >=0.12  # should be replaced by poetry-core
    - poetry-core
  run:
    - python
    - poetry >=0.12
    - __unix  # [unix]
    - __win   # [win]
    - colorama >=0.4.4,<5.0
    - mslex >=1.1.0,<2.0  # [win]
    - psutil >=5.7.2,<6.0
    - tomli >=2.0.1,<3.0

test:
  imports:
    - taskipy
  requires:
    - pip
  commands:
    - pip check
    - task --help

about:
  home: https://github.com/taskipy/taskipy
  summary: 'The complementary task runner for python projects'
  description: |
    Every development pipeline has tasks, such as test, lint or publish.
    With taskipy, you can define those tasks in one file and run them with a simple command.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/taskipy/taskipy

extra:
  recipe-maintainers:
    - Zeitsperre
    - illBeRoy
